user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}

http {
	include /etc/nginx/mime.types;
	default_type application/octet-stream;
	log_format main '$remote_addr - $remote_user [$time_local] "$request" '
									'$status $body_bytes_sent "$http_referer" '
									'"$http_user_agent" "$http_x_forwarded_for"';								
	access_log /var/log/nginx/access.log main;
	sendfile on;
	keepalive_timeout 65;

	# 请求体最大限制10m
	client_max_body_size 10m;
	# 哈希桶大小参数与处理器的缓存行大小对齐
	server_names_hash_bucket_size 64;

	# docker容器别名访问
	upstream ajax_service {
		server server:3000;
	}
	upstream webs_service {
		server server:8181;
	}

	# 配置缓存目录
	proxy_cache_path /usr/local/nginx-cache levels=1:2 keys_zone=nginx-cache:20m max_size=50g inactive=72h;

	# 本地访问配置，即：分别通过"localhost/portal/"、"localhost/admin/"访问花森起始页及后台管理界面
	server {
		gzip on;
		gzip_min_length 1k;
		gzip_buffers 4 16k;
		gzip_http_version 1.1;
		gzip_comp_level 8;
		gzip_types text/plain text/css text/javascript application/json application/xml application/javascript;
		gzip_disable "MSIE [1-6]\."; # 不压缩IE6及以下版本
		gzip_vary on;
		listen 80;
		server_name localhost;

		# ajax接口请求
		location /api/ {
			proxy_pass http://ajax_service/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header REMOTE-HOST $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		}
		# websocket实时通信
		location /ws/ {
			proxy_pass http://webs_service/;
			proxy_set_header Connection "upgrade";
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr; 
			proxy_set_header REMOTE-HOST $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		}
		# SEO 页面
		location /seo/ {
			add_header 'Cache-Control' "no-cache";
			proxy_pass http://ajax_service;
		}
		# public 静态资源直通
		location /public/ {
			add_header 'Cache-Control' "no-cache";
			proxy_pass http://ajax_service;
		}
		# bin 快捷脚本直通
		location /bin/ {
			add_header 'Cache-Control' "no-cache";
			proxy_pass http://ajax_service;
		}
		# huasen-store 静态资源直通
		location /huasen-store/ {
      add_header 'Cache-Control' "no-cache";
      proxy_pass http://ajax_service;
    }
		# 起始页和后台管理界面静态资源访问
		location ~ ^/(portal|admin|portal\/css|admin\/css)/huasen-store/ {
			add_header 'Cache-Control' "no-cache";
			rewrite ^/(portal|admin|portal\/css|admin\/css)/huasen-store/(.*) /huasen-store/$2 break;
    	proxy_pass http://ajax_service;
		}
		# 花森起始页
		location /portal/ {
			add_header 'Cache-Control' "no-cache";
			proxy_pass http://ajax_service/public/webapp/portal/;
		}
		# 花森后台管理界面
		location /admin/ {
			add_header 'Cache-Control' "no-cache";
			proxy_pass http://ajax_service/public/webapp/admin/;
		}
		# 花森个人页
		location / {
			add_header 'Cache-Control' "no-cache";
			proxy_pass http://ajax_service/huasen-store/webapp/guide/;
		}
		error_page 500 502 503 504 /50x.html;
		location = /50x.html {
			root /usr/share/nginx/html;
		}
	}
	# 默认配置
  include /etc/nginx/conf.d/*.conf;
}
